idf_component_register(
    SRCS
        "app_main.c"
        "i2c_bus.c"
        "lsm6dsr.c"
        "lis2mdl.c"
        "bmp388.c"
        "battery.c"
        "sensors.c"
        "diagnostics.c"
        "lcd_driver.c"
        "ui.c"
        "gnss.c"
        "input.c"
        "pbox.c"
    INCLUDE_DIRS "."
    REQUIRES
        esp_driver_gpio
        esp_driver_i2c
        esp_driver_spi
        esp_driver_ledc
        esp_driver_pcnt
        esp_driver_uart
        esp_adc
        esp_hal_ana_conv
        esp_lcd
        esp_lvgl_port
        esp_timer
        nvs_flash
)
